name: Node Continuous Integration

on:
  pull_request:
    branches: [main]

jobs:
  quality-assurance:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          cache: 'yarn'
      - run: yarn install
      - run: yarn build
      - run: yarn check:eslint
